version: "3.7"
services:
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    ports:
      - "1883:1883"
    restart: on-failure
  web:
    image: iot-back:latest
    hostname: iot-back
    depends_on: 
      - mosquitto
    ports:
      - "5000:5000" 