name: Continuous Integration

on: [push]

jobs:
  linting:
    name: Linting

    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v1
      - name: run wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.12.5

